#pragma config(Sensor, dgtl1,  b,              sensorDigitalIn)
#pragma config(Motor,  port2,           bba,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           bbb,           tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*struct Eric {
	unsigned int height;
	int schmuckiness; //Out of 10

};*/

//int e(int i){return !(i%2);}

/*task main()
{
	bLCDBacklight = true;

	/*struct Eric eric;
	eric.height = 5;
	eric.schmuckiness = 9;
	string S;
	sprintf(S, "%i", eric.height);
	displayLCDString(0,0,S);/
	char i; string S;
	for(i=1; i > 0; i++){
		sprintf(S, "%3d", i);
		displayLCDString(0,0,S);
		wait1Msec(100);
	}

	string brainfrickText;
	brainfrickText = "+-[]<>";

	signed char brainfrickStuff [256];
	unsigned char target;
	target = 0x00;
	unsigned int programCounter = 0;
	//To make it runnable, a few registers will be allocated to motors and stuff
	//0x01, 0x02, 0x03, 0x04 will be for channels on controller. 0x05, 0x06 will be for buttons. 0x07-0x10 i think for motors.
	//This is stupid

	while(1){

	}

}*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

task drive() {
	wait1msec(1000);
	motor[bbb] = motor[bba] = 100;
	wait1msec(1000);
	motor[bbb] = motor[bba] = 0;

	while(true) {
		if(SensorValue[b]) {
			motor[bbb] = motor[bba] = 100;
		} else {
			motor[bbb] = motor[bba] = 0;
		}
	}
}

task usercontrol() {

	startTask(drive);
}
